### ISSUE TITLE
Upload on pypi.

### ISSUE THREAD

**Issue by baldm** [Yepkit/pykush#9]
Hello,
Would it be possible to upload pykush to a pip library, at pypi.org?
There is an old python 2.7 version, but it appears to be from another developer.
I can also do it myself, with your permission of course.

**Comment by Bickio** [comment]
Doesn't answer your question, but may help your use case:

It is possible to install directly from github using pip. See https://pip.pypa.io/en/stable/topics/vcs-support/

**Comment by yep1** [comment]
Hello,

Yes you can publish it to a pip library.

Thanks for the collaboration.

Best Regards.

----- Original Message -----
From: baldm ***@***.***>
To Yepkit/pykush
Sent: Sun, Apr 03, 2022 at 09:00:05AM -0700
Subject: [Yepkit/pykush] Upload on pypi. (Issue #9)
